from django.db import models

class Zodiac(models.Model):
    entry_time = models.DateTimeField()
    name = models.CharField(max_length=100)
    datetime = models.CharField(max_length=100)
    # datetime = models.DateTimeField()
    point = models.CharField(max_length=100)
    zodiac = models.CharField(max_length=100)
    z_longitude = models.FloatField()
    house = models.IntegerField()
    RA = models.FloatField()
    lat = models.FloatField()
    lon = models.FloatField()

class Aspects(models.Model):
    entry_time = models.DateTimeField()
    name = models.CharField(max_length=100)
    datetime = models.CharField(max_length=100)
    # datetime = models.DateTimeField()
    body1 = models.CharField(max_length=100)
    body2 = models.CharField(max_length=100)
    shape = models.IntegerField()
    degree_type = models.CharField(max_length=20)
    degree = models.FloatField()
    lat = models.FloatField()
    lon = models.FloatField()

class User_info(models.Model):
    entry_time = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=100)
    datetime = models.CharField(max_length=100)
    year = models.IntegerField()
    month = models.IntegerField()
    day = models.IntegerField()
    hour =  models.IntegerField()
    minute =models.IntegerField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    natal_chart = models.ImageField(default='default.png', blank=True)
    aspect_grid = models.ImageField(default='default.png', blank=True)

class Stat_Images(models.Model):
    sun = models.ImageField(default='default.png', blank=True)
    moon = models.ImageField(default='default.png', blank=True)
    mercury = models.ImageField(default='default.png', blank=True)
    venus = models.ImageField(default='default.png', blank=True)
    mars = models.ImageField(default='default.png', blank=True)
    jupiter = models.ImageField(default='default.png', blank=True)
    saturn = models.ImageField(default='default.png', blank=True)
    uranus = models.ImageField(default='default.png', blank=True)
    neptune = models.ImageField(default='default.png', blank=True)
    pluto = models.ImageField(default='default.png', blank=True)
    ceres = models.ImageField(default='default.png', blank=True)
    chart_frame = models.ImageField(default='default.png', blank=True)
    aspact_frame = models.ImageField(default='default.png', blank=True)
    conjunction = models.ImageField(default='default.png', blank=True)
    opposition = models.ImageField(default='default.png', blank=True)
    square = models.ImageField(default='default.png', blank=True)
    sextile = models.ImageField(default='default.png', blank=True)
    trine = models.ImageField(default='default.png', blank=True)
    ids = models.IntegerField()