# Generated by Django 3.1.6 on 2021-02-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='aspect_grid',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='user_info',
            name='natal_chart',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
