# Generated by Django 3.1.6 on 2021-02-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20210219_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspects',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspects',
            name='lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zodiac',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zodiac',
            name='lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aspects',
            name='datetime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='datetime',
            field=models.CharField(max_length=100),
        ),
    ]
