# Generated by Django 3.1.6 on 2021-02-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_auto_20210219_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='datetime',
            field=models.CharField(default='nan', max_length=100),
            preserve_default=False,
        ),
    ]
