# Generated by Django 3.1.6 on 2021-02-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_user_info_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspects',
            name='degree_type',
            field=models.CharField(max_length=20),
        ),
    ]
