# Generated by Django 3.1.6 on 2021-03-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0006_stat_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat_images',
            name='ids',
            field=models.IntegerField(default=101),
            preserve_default=False,
        ),
    ]
