# Generated by Django 3.1.6 on 2021-03-03 06:49

import django.contrib.postgres.fields.ranges
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0009_auto_20210301_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='day',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='hour',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='minute',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='month',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='year',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
