# Generated by Django 3.1.6 on 2021-03-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0013_auto_20210303_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspects',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
