# Generated by Django 3.1.6 on 2021-03-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0016_magnetic_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnetic_data',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magnetic_data',
            name='lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
