# Generated by Django 3.1.6 on 2021-03-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0018_magnetic_data_area_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnetic_data',
            name='observatory',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
